swagger: "2.0"
info:
    description: "This will have content of description for your api"
    version: "1.0.0"
    title: "API Documentation Example"
host: "localhost:3000"
basePath: "/api/v1"
paths:
    /login:
        post:
            summary: "Login"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "email"
                          - "password"
                      properties:
                          email:
                              type: "string"
                          password:
                              type: "string"
            responses:
                "200":
                    description: "OK"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        userCredentials:
                                            $ref: "#/definitions/userCredentials"
                                        token:
                                            type: "string"
                "400":
                    description: "Server Error"
                    $ref: "#/definitions/errorResponse"

    /register:
        post:
            summary: "Register"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "name"
                          - "username"
                          - "email"
                          - "password"
                      properties:
                          name:
                              type: "string"
                          username:
                              type: "string"
                          email:
                              type: "string"
                          password:
                              type: "string"
            responses:
                "200":
                    description: "OK"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        userCredentials:
                                            $ref: "#/definitions/userCredentials"
                "400":
                    description: "Server Error"
                    $ref: "#/definitions/errorResponse"

    /whoami:
        get:
            summary: "Who am I"
            description: ""
            produces:
                - "application/json"
            responses:
                "200":
                    description: "OK"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        id:
                                            type: "integer"
                                        name:
                                            type: "string"
                                        username:
                                            type: "string"
                                        email:
                                            type: "string"
                "400":
                    description: "Server Error"
                    $ref: "#/definitions/errorResponse"
            security:
                - bearerAuth: []

# Authorization
securityDefinitions:
    bearerAuth:
        name: Authorization # arbitrary name for the security scheme
        type: apiKey
        scheme: bearer
        in: header

definitions:
    # userResponse
    userCredentials:
        type: "object"
        properties:
            id:
                type: "integer"
            roleId:
                type: "integer"
            name:
                type: "string"
            username:
                type: "string"
            email:
                type: "string"
            isActive:
                type: "boolean"
            createdAt:
                type: "string"
                format: "date-time"
            updatedAt:
                type: "string"
                format: "date-time"
    # errorResponse
    errorResponse:
        schema:
            items:
                type: "object"
                properties:
                    error:
                        type: "string"
                    message:
                        type: "string"
