swagger: "2.0"
info:
    description: "This will have content of description for your api"
    version: "1.0.0"
    title: "API Documentation Example"
host: "localhost:3000"
basePath: "/api"
paths:
    /user/login:
        post:
            summary: "Login"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "username"
                          - "password"
                      properties:
                          username:
                              type: "string"
                          password:
                              type: "string"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        token:
                                            type: "string"
                                error:
                                    type: "string"
                "400":
                    description: "Server Error"

    /category/list:
        get:
            summary: "List of category"
            description: ""
            produces:
                - "application/json"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        type: "array"
                        items:
                            $ref: "#/definitions/CategoryResponse"
                "400":
                    description: "Server Error"
            security:
                - bearerAuth: []
    /category/create:
        post:
            summary: "Create category"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "name"
                          - "description"
                      properties:
                          name:
                              type: "string"
                          description:
                              type: "string"
                          is_active:
                              type: "boolean"
                              default: true
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        items:
                            $ref: "#/definitions/CategoryResponse"
                "400":
                    description: "Server Error"
    /category/update:
        put:
            summary: "Update category"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "name"
                          - "id"
                          - "description"
                      properties:
                          id:
                              type: "integer"
                          name:
                              type: "string"
                          description:
                              type: "string"
                          is_active:
                              type: "boolean"
                              default: true
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        items:
                            $ref: "#/definitions/CategoryResponse"
                "400":
                    description: "Server Error"
            security:
                - bearerAuth: []
    /category/destroy:
        delete:
            summary: "Destroy category"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "id"
                      properties:
                          id:
                              type: "integer"
            responses:
                "200":
                    description: "successful operation"
                    schema:
                        items:
                            $ref: "#/definitions/CategoryResponse"
                "400":
                    description: "Server Error"
            security:
                - bearerAuth: []

securityDefinitions:
    bearerAuth:
        name: Authorization # arbitrary name for the security scheme
        type: apiKey
        scheme: bearer
        in: header

definitions:
    CategoryResponse:
        type: "object"
        properties:
            success:
                type: "boolean"
                default: true
            message:
                type: "string"
            data:
                type: "object"
                properties:
                    name:
                        type: "string"
                    description:
                        type: "string"
                    is_active:
                        type: "boolean"
                        default: true
            error:
                type: "string"
