swagger: "2.0"
info:
    description: "This will have content of description for your api"
    version: "1.0.0"
    title: "API Documentation Example"
host: "localhost:3000"
basePath: "/api/v1"
paths:
    /login:
        post:
            summary: "Login"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "email"
                          - "password"
                      properties:
                          email:
                              type: "string"
                          password:
                              type: "string"
            responses:
                "200":
                    description: "OK"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        userCredential:
                                            type: "object"
                                            properties:
                                                id:
                                                    type: "integer"
                                                name:
                                                    type: "string"
                                                username:
                                                    type: "string"
                                                email:
                                                    type: "string"
                                                password:
                                                    type: "string"
                                                isActive:
                                                    type: "boolean"
                                                roleId:
                                                    type: "integer"
                                                createdAt:
                                                    type: "string"
                                                    format: "date-time"
                                                updatedAt:
                                                    type: "string"
                                                    format: "date-time"
                                        token:
                                            type: "string"
                                error:
                                    type: "string"
                "400":
                    description: "Server Error"

    /register:
        post:
            summary: "Register"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "body"
                  in: "body"
                  required: true
                  schema:
                      type: "object"
                      required:
                          - "name"
                          - "username"
                          - "email"
                          - "password"
                      properties:
                          name:
                              type: "string"
                          username:
                              type: "string"
                          email:
                              type: "string"
                          password:
                              type: "string"
            responses:
                "200":
                    description: "OK"
                    schema:
                        items:
                            type: "object"
                            properties:
                                success:
                                    type: "boolean"
                                    default: true
                                message:
                                    type: "string"
                                data:
                                    type: "object"
                                    properties:
                                        isActive:
                                            type: "boolean"
                                        roleId:
                                            type: "integer"
                                        id:
                                            type: "integer"
                                        name:
                                            type: "string"
                                        username:
                                            type: "string"
                                        email:
                                            type: "string"
                                        password:
                                            type: "string"
                                        updatedAt:
                                            type: "string"
                                            format: "date-time"
                                        createdAt:
                                            type: "string"
                                            format: "date-time"
                                error:
                                    type: "string"
                "400":
                    description: "Server Error"
